[
  {
    "cmd": "delete-by-query",
    "query": {
      "contexts": [
        "package"
      ],
      "query": {
        "op": "case",
        "type": "word",
        "word": "stable-memo"
      },
      "type": "context"
    }
  },
  [
    {
      "cmd": "insert",
      "document": {
        "description": {
          "description": "\u003cdiv class=\"doc\"\u003e\u003cp\u003eThis module provides memo combinators with slightly different behavior\nfrom those in \u003ca\u003eData.StableMemo\u003c/a\u003e. The memo tables generated by these\ncombinators use weak pointers to store the values, so they not only do\nnot unnecessarily retain the arguments, but they also do not retain\nthe function outputs. This can be useful for memoized functions that\nare expected to be around for a long time. If the result for an input\nhas already been computed and happens to still be in the heap, it will\nbe reused, otherwise it will be recomputed.\n\u003c/p\u003e\u003c/div\u003e",
          "module": "Data.StableMemo.Weak",
          "name": "Weak",
          "package": "stable-memo",
          "source": "src/Data-StableMemo-Weak.html",
          "type": "module"
        },
        "index": {
          "description": "This module provides memo combinators with slightly different behavior from those in Data.StableMemo The memo tables generated by these combinators use weak pointers to store the values so they not only do not unnecessarily retain the arguments but they also do not retain the function outputs This can be useful for memoized functions that are expected to be around for long time If the result for an input has already been computed and happens to still be in the heap it will be reused otherwise it will be recomputed",
          "hierarchy": "Data StableMemo Weak",
          "module": "Data.StableMemo.Weak",
          "name": "Weak",
          "package": "stable-memo",
          "partial": "Weak",
          "type": "module"
        },
        "uri": "http://hackage.haskell.org/package/stable-memo/docs/Data-StableMemo-Weak.html#"
      }
    },
    {
      "cmd": "insert",
      "document": {
        "description": {
          "description": "\u003cp\u003ePolymorphic memoizable function\n\u003c/p\u003e",
          "module": "Data.StableMemo.Weak",
          "name": "(--\u003e)",
          "package": "stable-memo",
          "source": "src/Data-StableMemo-Internal.html#--%3E",
          "type": "type"
        },
        "index": {
          "description": "Polymorphic memoizable function",
          "hierarchy": "Data StableMemo Weak",
          "module": "Data.StableMemo.Weak",
          "name": "(--\u003e) --\u003e",
          "package": "stable-memo",
          "type": "type"
        },
        "uri": "http://hackage.haskell.org/package/stable-memo/docs/Data-StableMemo-Weak.html#t:-45--45--62-"
      }
    },
    {
      "cmd": "insert",
      "document": {
        "description": {
          "description": "\u003cp\u003eMemoize a unary function.\n\u003c/p\u003e",
          "module": "Data.StableMemo.Weak",
          "name": "memo",
          "package": "stable-memo",
          "signature": "(a -\u003e b) -\u003e a -\u003e b",
          "source": "src/Data-StableMemo-Weak.html#memo",
          "type": "function"
        },
        "index": {
          "description": "Memoize unary function",
          "hierarchy": "Data StableMemo Weak",
          "module": "Data.StableMemo.Weak",
          "name": "memo",
          "normalized": "(a-\u003eb)-\u003ea-\u003eb",
          "package": "stable-memo",
          "signature": "(a-\u003eb)-\u003ea-\u003eb",
          "type": "function"
        },
        "uri": "http://hackage.haskell.org/package/stable-memo/docs/Data-StableMemo-Weak.html#v:memo"
      }
    },
    {
      "cmd": "insert",
      "document": {
        "description": {
          "description": "\u003cp\u003eCurried memoization to share partial evaluation\n\u003c/p\u003e",
          "module": "Data.StableMemo.Weak",
          "name": "memo2",
          "package": "stable-memo",
          "signature": "(a -\u003e b -\u003e c) -\u003e a -\u003e b -\u003e c",
          "source": "src/Data-StableMemo-Weak.html#memo2",
          "type": "function"
        },
        "index": {
          "description": "Curried memoization to share partial evaluation",
          "hierarchy": "Data StableMemo Weak",
          "module": "Data.StableMemo.Weak",
          "name": "memo2",
          "normalized": "(a-\u003eb-\u003ec)-\u003ea-\u003eb-\u003ec",
          "package": "stable-memo",
          "signature": "(a-\u003eb-\u003ec)-\u003ea-\u003eb-\u003ec",
          "type": "function"
        },
        "uri": "http://hackage.haskell.org/package/stable-memo/docs/Data-StableMemo-Weak.html#v:memo2"
      }
    },
    {
      "cmd": "insert",
      "document": {
        "description": {
          "description": "\u003cp\u003eCurried memoization to share partial evaluation\n\u003c/p\u003e",
          "module": "Data.StableMemo.Weak",
          "name": "memo3",
          "package": "stable-memo",
          "signature": "(a -\u003e b -\u003e c -\u003e d) -\u003e a -\u003e b -\u003e c -\u003e d",
          "source": "src/Data-StableMemo-Weak.html#memo3",
          "type": "function"
        },
        "index": {
          "description": "Curried memoization to share partial evaluation",
          "hierarchy": "Data StableMemo Weak",
          "module": "Data.StableMemo.Weak",
          "name": "memo3",
          "normalized": "(a-\u003eb-\u003ec-\u003ed)-\u003ea-\u003eb-\u003ec-\u003ed",
          "package": "stable-memo",
          "signature": "(a-\u003eb-\u003ec-\u003ed)-\u003ea-\u003eb-\u003ec-\u003ed",
          "type": "function"
        },
        "uri": "http://hackage.haskell.org/package/stable-memo/docs/Data-StableMemo-Weak.html#v:memo3"
      }
    },
    {
      "cmd": "insert",
      "document": {
        "description": {
          "description": "\u003cp\u003eMemoize a function with support for a certain form of polymorphic\n recursion.\n\u003c/p\u003e",
          "module": "Data.StableMemo.Weak",
          "name": "memoPoly",
          "package": "stable-memo",
          "signature": "(f --\u003e g) -\u003e f --\u003e g",
          "source": "src/Data-StableMemo-Weak.html#memoPoly",
          "type": "function"
        },
        "index": {
          "description": "Memoize function with support for certain form of polymorphic recursion",
          "hierarchy": "Data StableMemo Weak",
          "module": "Data.StableMemo.Weak",
          "name": "memoPoly",
          "normalized": "(a-\u003eb)-\u003ea-\u003eb",
          "package": "stable-memo",
          "partial": "Poly",
          "signature": "(f-\u003eg)-\u003ef-\u003eg",
          "type": "function"
        },
        "uri": "http://hackage.haskell.org/package/stable-memo/docs/Data-StableMemo-Weak.html#v:memoPoly"
      }
    },
    {
      "cmd": "insert",
      "document": {
        "description": {
          "module": "Data.StableMemo",
          "name": "StableMemo",
          "package": "stable-memo",
          "source": "src/Data-StableMemo.html",
          "type": "module"
        },
        "index": {
          "hierarchy": "Data StableMemo",
          "module": "Data.StableMemo",
          "name": "StableMemo",
          "package": "stable-memo",
          "partial": "Stable Memo",
          "type": "module"
        },
        "uri": "http://hackage.haskell.org/package/stable-memo/docs/Data-StableMemo.html#"
      }
    },
    {
      "cmd": "insert",
      "document": {
        "description": {
          "description": "\u003cp\u003ePolymorphic memoizable function\n\u003c/p\u003e",
          "module": "Data.StableMemo",
          "name": "(--\u003e)",
          "package": "stable-memo",
          "source": "src/Data-StableMemo-Internal.html#--%3E",
          "type": "type"
        },
        "index": {
          "description": "Polymorphic memoizable function",
          "hierarchy": "Data StableMemo",
          "module": "Data.StableMemo",
          "name": "(--\u003e) --\u003e",
          "package": "stable-memo",
          "type": "type"
        },
        "uri": "http://hackage.haskell.org/package/stable-memo/docs/Data-StableMemo.html#t:-45--45--62-"
      }
    },
    {
      "cmd": "insert",
      "document": {
        "description": {
          "description": "\u003cp\u003eMemoize a unary function.\n\u003c/p\u003e",
          "module": "Data.StableMemo",
          "name": "memo",
          "package": "stable-memo",
          "signature": "(a -\u003e b) -\u003e a -\u003e b",
          "source": "src/Data-StableMemo.html#memo",
          "type": "function"
        },
        "index": {
          "description": "Memoize unary function",
          "hierarchy": "Data StableMemo",
          "module": "Data.StableMemo",
          "name": "memo",
          "normalized": "(a-\u003eb)-\u003ea-\u003eb",
          "package": "stable-memo",
          "signature": "(a-\u003eb)-\u003ea-\u003eb",
          "type": "function"
        },
        "uri": "http://hackage.haskell.org/package/stable-memo/docs/Data-StableMemo.html#v:memo"
      }
    },
    {
      "cmd": "insert",
      "document": {
        "description": {
          "description": "\u003cp\u003eCurried memoization to share partial evaluation\n\u003c/p\u003e",
          "module": "Data.StableMemo",
          "name": "memo2",
          "package": "stable-memo",
          "signature": "(a -\u003e b -\u003e c) -\u003e a -\u003e b -\u003e c",
          "source": "src/Data-StableMemo.html#memo2",
          "type": "function"
        },
        "index": {
          "description": "Curried memoization to share partial evaluation",
          "hierarchy": "Data StableMemo",
          "module": "Data.StableMemo",
          "name": "memo2",
          "normalized": "(a-\u003eb-\u003ec)-\u003ea-\u003eb-\u003ec",
          "package": "stable-memo",
          "signature": "(a-\u003eb-\u003ec)-\u003ea-\u003eb-\u003ec",
          "type": "function"
        },
        "uri": "http://hackage.haskell.org/package/stable-memo/docs/Data-StableMemo.html#v:memo2"
      }
    },
    {
      "cmd": "insert",
      "document": {
        "description": {
          "description": "\u003cp\u003eCurried memoization to share partial evaluation\n\u003c/p\u003e",
          "module": "Data.StableMemo",
          "name": "memo3",
          "package": "stable-memo",
          "signature": "(a -\u003e b -\u003e c -\u003e d) -\u003e a -\u003e b -\u003e c -\u003e d",
          "source": "src/Data-StableMemo.html#memo3",
          "type": "function"
        },
        "index": {
          "description": "Curried memoization to share partial evaluation",
          "hierarchy": "Data StableMemo",
          "module": "Data.StableMemo",
          "name": "memo3",
          "normalized": "(a-\u003eb-\u003ec-\u003ed)-\u003ea-\u003eb-\u003ec-\u003ed",
          "package": "stable-memo",
          "signature": "(a-\u003eb-\u003ec-\u003ed)-\u003ea-\u003eb-\u003ec-\u003ed",
          "type": "function"
        },
        "uri": "http://hackage.haskell.org/package/stable-memo/docs/Data-StableMemo.html#v:memo3"
      }
    },
    {
      "cmd": "insert",
      "document": {
        "description": {
          "description": "\u003cp\u003eMemoize a function with support for a certain form of polymorphic\n recursion.\n\u003c/p\u003e",
          "module": "Data.StableMemo",
          "name": "memoPoly",
          "package": "stable-memo",
          "signature": "(f --\u003e g) -\u003e f --\u003e g",
          "source": "src/Data-StableMemo.html#memoPoly",
          "type": "function"
        },
        "index": {
          "description": "Memoize function with support for certain form of polymorphic recursion",
          "hierarchy": "Data StableMemo",
          "module": "Data.StableMemo",
          "name": "memoPoly",
          "normalized": "(a-\u003eb)-\u003ea-\u003eb",
          "package": "stable-memo",
          "partial": "Poly",
          "signature": "(f-\u003eg)-\u003ef-\u003eg",
          "type": "function"
        },
        "uri": "http://hackage.haskell.org/package/stable-memo/docs/Data-StableMemo.html#v:memoPoly"
      }
    }
  ]
]