[
  {
    "cmd": "update",
    "document": {
      "uri": "http://hackage.haskell.org/package/vacuum-opengl/docs/System-Vacuum-OpenGL-Client.html#",
      "description": {
        "fct-descr": "\u003cdiv class=\"doc\"\u003e\u003cp\u003eSince GLUT+GHCi is problematic at best, after some very frustating\n experiments I decided on a client-server architecture.\n\u003c/p\u003e\u003cp\u003eUsage example:\n\u003c/p\u003e\u003cpre\u003e $ vacuum-opengl-server &\n vacuum-opengl server started - press ESC to exit. \n listening on port 55961\n \n $ ghci\n Prelude\u003e :m + System.Vacuum.OpenGL \n Prelude System.Vacuum.OpenGL\u003e view [1..5]\n Prelude System.Vacuum.OpenGL\u003e view $ zip \"foobar\" [1..6]\n Prelude System.Vacuum.OpenGL\u003e :m + Data.Set\n Prelude System.Vacuum.OpenGL Data.Set\u003e view $ fromList [1..10]\n\u003c/pre\u003e\u003cp\u003eNote: \n\u003c/p\u003e\u003cul\u003e\u003cli\u003e we need the graphviz executable (called \"dot\") being in the path.\n\u003c/li\u003e\u003cli\u003e we need the server running\n\u003c/li\u003e\u003cli\u003e the image generated by graphviz may be bigger than the maximum texture \n    size your video card supports (eg. 2048). In this case you will see\n    a white rectangle. TODO: handle this better.\n\u003c/li\u003e\u003c/ul\u003e\u003cp\u003eTODO:\n\u003c/p\u003e\u003cul\u003e\u003cli\u003e zooming & panning with mouse\n\u003c/li\u003e\u003cli\u003e nicer graph labels\n\u003c/li\u003e\u003c/ul\u003e\u003c/div\u003e",
        "fct-module": "System.Vacuum.OpenGL.Client",
        "fct-package": "vacuum-opengl",
        "fct-signature": "module",
        "fct-source": "src/System-Vacuum-OpenGL-Client.html",
        "fct-type": "module",
        "title": "Client"
      },
      "index": {
        "description": "Since GLUT GHCi is problematic at best after some very frustating experiments decided on client-server architecture Usage example vacuum-opengl-server vacuum-opengl server started press ESC to exit listening on port ghci Prelude System.Vacuum.OpenGL Prelude System.Vacuum.OpenGL view Prelude System.Vacuum.OpenGL view zip foobar Prelude System.Vacuum.OpenGL Data.Set Prelude System.Vacuum.OpenGL Data.Set view fromList Note we need the graphviz executable called dot being in the path we need the server running the image generated by graphviz may be bigger than the maximum texture size your video card supports eg In this case you will see white rectangle TODO handle this better TODO zooming panning with mouse nicer graph labels",
        "hierarchy": "System Vacuum OpenGL Client",
        "module": "System.Vacuum.OpenGL.Client",
        "name": "Client",
        "normalized": "",
        "package": "vacuum-opengl",
        "partial": "Client",
        "signature": ""
      }
    }
  },
  {
    "cmd": "update",
    "document": {
      "uri": "http://hackage.haskell.org/package/vacuum-opengl/docs/System-Vacuum-OpenGL-Client.html#v:changeHost",
      "description": {
        "fct-module": "System.Vacuum.OpenGL.Client",
        "fct-package": "vacuum-opengl",
        "fct-signature": "String -\u003e IO ()",
        "fct-source": "src/System-Vacuum-OpenGL-Client.html#changeHost",
        "fct-type": "function",
        "title": "changeHost"
      },
      "index": {
        "description": "",
        "hierarchy": "System Vacuum OpenGL Client",
        "module": "System.Vacuum.OpenGL.Client",
        "name": "changeHost",
        "normalized": "String-\u003eIO()",
        "package": "vacuum-opengl",
        "partial": "Host",
        "signature": "String-\u003eIO()"
      }
    }
  },
  {
    "cmd": "update",
    "document": {
      "uri": "http://hackage.haskell.org/package/vacuum-opengl/docs/System-Vacuum-OpenGL-Client.html#v:changePort",
      "description": {
        "fct-module": "System.Vacuum.OpenGL.Client",
        "fct-package": "vacuum-opengl",
        "fct-signature": "Int -\u003e IO ()",
        "fct-source": "src/System-Vacuum-OpenGL-Client.html#changePort",
        "fct-type": "function",
        "title": "changePort"
      },
      "index": {
        "description": "",
        "hierarchy": "System Vacuum OpenGL Client",
        "module": "System.Vacuum.OpenGL.Client",
        "name": "changePort",
        "normalized": "Int-\u003eIO()",
        "package": "vacuum-opengl",
        "partial": "Port",
        "signature": "Int-\u003eIO()"
      }
    }
  },
  {
    "cmd": "update",
    "document": {
      "uri": "http://hackage.haskell.org/package/vacuum-opengl/docs/System-Vacuum-OpenGL-Client.html#v:view",
      "description": {
        "fct-module": "System.Vacuum.OpenGL.Client",
        "fct-package": "vacuum-opengl",
        "fct-signature": "a -\u003e IO ()",
        "fct-source": "src/System-Vacuum-OpenGL-Client.html#view",
        "fct-type": "function",
        "title": "view"
      },
      "index": {
        "description": "",
        "hierarchy": "System Vacuum OpenGL Client",
        "module": "System.Vacuum.OpenGL.Client",
        "name": "view",
        "normalized": "a-\u003eIO()",
        "package": "vacuum-opengl",
        "partial": "",
        "signature": "a-\u003eIO()"
      }
    }
  },
  {
    "cmd": "update",
    "document": {
      "uri": "http://hackage.haskell.org/package/vacuum-opengl/docs/System-Vacuum-OpenGL.html#",
      "description": {
        "fct-module": "System.Vacuum.OpenGL",
        "fct-package": "vacuum-opengl",
        "fct-signature": "module",
        "fct-source": "src/System-Vacuum-OpenGL.html",
        "fct-type": "module",
        "title": "OpenGL"
      },
      "index": {
        "description": "",
        "hierarchy": "System Vacuum OpenGL",
        "module": "System.Vacuum.OpenGL",
        "name": "OpenGL",
        "normalized": "",
        "package": "vacuum-opengl",
        "partial": "Open GL",
        "signature": ""
      }
    }
  }
]